# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_ARCH_ASPEED) += \
	ast2700-evb.dtb \
	ast2700-evb_ast1700-evb.dtb \
	ast2700-dcscm.dtb \
	ast2700-dcscm_ast1700-demo.dtb \
	ast2700-dcscm_ast1700-evb.dtb \
